### PR TITLE
Create Panoview_edited.jpg

### PR DESCRIPTION
**Pull request by bipulkmr-crypto**
Issue: 4

#### Short description of what this resolves:

This gives the app a logo.

#### Changes proposed in this pull request and/or Screenshots of changes:

-Added a logo for the App (Panoviewer) depicting the app's name along with a beautiful panoramic  image-

### CODE REVIEW

**Comment by GhostFoxSledgehammer** [comment]
Attached image is not related to the project, try to create something logo-ish related to either panoramic images or image viewer or both. See issue description for example.

**Comment by bipulkmr-crypto** [comment]
> Attached image is not related to the project, try to create something logo-ish related to either panoramic images or image viewer or both. See issue description for example.

Ok sir making nessecary changes.

**Comment by bipulkmr-crypto** [comment]
Sir please check if the present logo matches the current parameters

**Comment by GhostFoxSledgehammer** [comment]
Please change the target branch to [dev](https://github.com/opencodeiiita/PanoViewer/tree/dev)

**Comment by bipulkmr-crypto** [comment]
> Please change the target branch to [dev](https://github.com/opencodeiiita/PanoViewer/tree/dev)

Closing this  PR and creating a new one.

**Pull request closed without merging**
