### PR TITLE
rearranged menubar

### PR DESCRIPTION
**Pull request by Tanushree-coder**
Issue: 105

#### Short description of what this resolves:

rearranged menubar as File -> Mode -> Options -> About.

#### Changes proposed in this pull request and/or Screenshots of changes:

image

### CODE REVIEW

**Comment by Tanushree-coder** [comment]
@GhostFoxSledgehammer  sir pls review!

**Review by GhostFoxSledgehammer — COMMENTED** [review]
image
Nothing happens when about is pressed(Is it working in your system?). This may be because you have defined About as an `Menu` instead of `MenuItem`. I don't think menu works same as menuitem although Menu class extends MenuItem. I'll look into this in more detail after some time.

For now you can revert back to previous design(About inside of Help).

**Comment by Tanushree-coder** [comment]
> image Nothing happens when about is pressed(Is it working in your system?). This may be because you have defined About as an `Menu` instead of `MenuItem`. I don't think menu works same as menuitem although Menu class extends MenuItem. I'll look into this in more detail after some time.
> 
> For now you can revert back to previous design(About inside of Help).

yes. it wasn't working in my system also.
I've reverted back the changes.

**Comment by GhostFoxSledgehammer** [comment]
Looks good.

**Pull request merged**
