### PR TITLE
Madhur's Commit

### PR DESCRIPTION
**Pull request by mjmadhur**
Issue: 3

#### Short description of what this resolves:
-  Added A logo for what the app actually explains

#### Changes proposed in this pull request and/or Screenshots of changes:
 - Created A new Folder Images to Store the Logo in it

### CODE REVIEW

**Comment by mjmadhur** [comment]
please check if now the pr template  is correct!!

**Comment by mjmadhur** [comment]
Sorry it Was closed By mistake

**Comment by GhostFoxSledgehammer** [comment]
Your images doesn't seem to be original, did you create them?
[Logo](https://clp.law.harvard.edu/assets/services-360-video-340x315.jpg) [Harvard CLP](https://clp.law.harvard.edu/assets/services-360-video-340x315.jpg)
[Logo2](https://stock.adobe.com/301995048?tduid=d40cf88335134f775dee5c54a5815871&as_channel=affiliate&as_campclass=redirect&as_source=arvato)

**Comment by mjmadhur** [comment]
I Will resend you new one

**Comment by mjmadhur** [comment]
Now i have added logo again.plss go through it.

**Comment by GhostFoxSledgehammer** [comment]
Good Work!

**Pull request merged**
