### PR TITLE
added logo

### PR DESCRIPTION
**Pull request by codesanta142**
Issue: 3

#### Short description of what this resolves:
Added logo for the project

#### Changes proposed in this pull request and/or Screenshots of changes:

-
codesanat142_logo

-
-

### CODE REVIEW

**Comment by GhostFoxSledgehammer** [comment]
I can see individual components scattered on the internet without permissive licenses. Have you created them yourself or have you obtained them with license to modify without acknowledgement from any other source?

[360 logo](https://www.freepik.com/premium-vector/360-degree-camera-sticker-logo-icon-vector-panorama-picture-360-degree-camera-photo-icon-virtual-reality-front-camera-swap-vector-isolated-background-eps-10_17449889.htm#page=1&query=360%20logo&position=9&from_view=keyword)
[Visual Icon](https://www.iconfinder.com/icons/2487999/eye_view_visib%3Be_visual_icon)

**Comment by codesanta142** [comment]
> I can see individual components scattered on the internet without permissive licenses. Have you created them yourself or have you obtained them with license to modify without acknowledgement from any other source?
> 
> [360 logo](https://www.freepik.com/premium-vector/360-degree-camera-sticker-logo-icon-vector-panorama-picture-360-degree-camera-photo-icon-virtual-reality-front-camera-swap-vector-isolated-background-eps-10_17449889.htm#page=1&query=360%20logo&position=9&from_view=keyword) [Visual Icon](https://www.iconfinder.com/icons/2487999/eye_view_visib%3Be_visual_icon)

@GhostFoxSledgehammer sir i used canva elements , we cant use them?

**Comment by GhostFoxSledgehammer** [comment]
> 
> 
> > I can see individual components scattered on the internet without permissive licenses. Have you created them yourself or have you obtained them with license to modify without acknowledgement from any other source?
> > [360 logo](https://www.freepik.com/premium-vector/360-degree-camera-sticker-logo-icon-vector-panorama-picture-360-degree-camera-photo-icon-virtual-reality-front-camera-swap-vector-isolated-background-eps-10_17449889.htm#page=1&query=360%20logo&position=9&from_view=keyword) [Visual Icon](https://www.iconfinder.com/icons/2487999/eye_view_visib%3Be_visual_icon)
> 
> @GhostFoxSledgehammer sir i used canva elements , we cant use them?

Can you provide links to were you got them from?

**Comment by codesanta142** [comment]
@GhostFoxSledgehammer sir they were available in canva 

image

**Comment by GhostFoxSledgehammer** [comment]
> 
> 
> @GhostFoxSledgehammer sir they were available in canva
> 
> image

Okay, seems legit.
Good Work!

**Comment by codesanta142** [comment]
> > @GhostFoxSledgehammer sir they were available in canva
> > image
> 
> Okay, seems legit. Good Work!

Thanks sir

**Pull request merged**
