### PR TITLE
Added Logo

### PR DESCRIPTION
**Pull request by Ms-Error**
Issue: 3

#### Short description of what this resolves:
added logo for PanoViewer project.

#### Changes proposed in this pull request and/or Screenshots of changes:
logo

### CODE REVIEW

**Comment by GhostFoxSledgehammer** [comment]
Where did you get this part from?
image

**Comment by Ms-Error** [comment]
https://www.google.com/imgres?imgurl=https://cdn.iconscout.com/icon/free/png-256/panorama-6-429196.png&imgrefurl=https://iconscout.com/icon/panorama-6&h=256&w=256&tbnid=JMMFsUB_K1NKXM&tbnh=225&tbnw=225&osm=1&hcb=1&source=lens-native&usg=AI4_-kRPr33bT9v1_pPftIHpHx_jBGzOBA&docid=n1U6U5O88qbEHM#imgrc=dZ-cJnauC6uVvM&imgdii=pW--eQEd-ijhIM

**Comment by GhostFoxSledgehammer** [comment]
> 
> 
> https://www.google.com/imgres?imgurl=https://cdn.iconscout.com/icon/free/png-256/panorama-6-429196.png&imgrefurl=https://iconscout.com/icon/panorama-6&h=256&w=256&tbnid=JMMFsUB_K1NKXM&tbnh=225&tbnw=225&osm=1&hcb=1&source=lens-native&usg=AI4_-kRPr33bT9v1_pPftIHpHx_jBGzOBA&docid=n1U6U5O88qbEHM#imgrc=dZ-cJnauC6uVvM&imgdii=pW--eQEd-ijhIM

Okay so the website doesn't require attributions so I'm accepting this.
Good Work!

**Comment by GhostFoxSledgehammer** [comment]
You need to change image name to `Ms-Error_logo.png`

**Pull request closed without merging**
